mixed-port: 7899
allow-lan: true
mode: rule
log-level: info

external-controller: 0.0.0.0:9090
secret: "Duoduo0210."

profile:
  store-selected: true
  store-fake-ip: true

dns:
  enable: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - nextcloud-aio-apache
    - nextcloud-aio-database
    - nextcloud-aio-nextcloud
    - nextcloud-aio-redis
    - nextcloud-aio-notify-push
    - nextcloud-aio-talk
    - nextcloud-aio-imaginary
    - nextcloud-aio-whiteboard
    - mp.weixin.qq.com
    - mmbiz.qpic.cn
    - mmbiz.qlogo.cn
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query

tun:
  enable: true
  stack: mixed
  auto-route: true
  auto-detect-interface: true

listeners:
  - name: port_auto
    type: mixed
    port: 7891
    listen: 0.0.0.0
    rule: auto-in

proxy-providers:
  sub-1:
    type: http
    url: "第一个链接"
    interval: 86400
    path: ./providers/sub-1.yaml
    health-check:
      enable: true
      interval: 600
      url: https://www.gstatic.com/generate_204

  sub-2:
    type: http
    url: "第二个链接"
    interval: 86400
    path: ./providers/sub-2.yaml
    health-check:
      enable: true
      interval: 600
      url: https://www.gstatic.com/generate_204

proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - AUTO
      - DIRECT
    use:
      - sub-1
      - sub-2

  - name: AUTO
    type: url-test
    use:
      - sub-1
      - sub-2
    url: https://www.gstatic.com/generate_204
    interval: 600
    tolerance: 50

sub-rules:
  auto-in:
    # 1. Steam 游戏/客户端更新下载（直连）
    - DOMAIN-SUFFIX,steamcontent.com,DIRECT
    - DOMAIN-SUFFIX,steamserver.net,DIRECT
    - DOMAIN-SUFFIX,steampipe.akamaized.net,DIRECT
    - DOMAIN-KEYWORD,steamcontent,DIRECT
    - DOMAIN-KEYWORD,steampipe,DIRECT
    # Steam 中国区实际下发的第三方下载 CDN
    - DOMAIN,dl.steam.clngaa.com,DIRECT
    - DOMAIN,dl.steam.cyngaa.com,DIRECT
    - DOMAIN,st.dl.eccdnx.com,DIRECT
    - DOMAIN,xz.pphimalayanrt.com,DIRECT
    - DOMAIN,yif.gdtstream.com,DIRECT
    - DOMAIN,gstore.val.smogfly.com,DIRECT

    # 2. Steam 商店 / 社区及其静态资源（走代理）
    - DOMAIN,store.steampowered.com,PROXY
    - DOMAIN,checkout.steampowered.com,PROXY
    - DOMAIN,help.steampowered.com,PROXY
    - DOMAIN-SUFFIX,steamcommunity.com,PROXY
    - DOMAIN-SUFFIX,steamstatic.com,PROXY
    - DOMAIN-SUFFIX,steamusercontent.com,PROXY
    - DOMAIN,steamcommunity-a.akamaihd.net,PROXY
    - DOMAIN,steamstore-a.akamaihd.net,PROXY
    - DOMAIN,steamusercontent-a.akamaihd.net,PROXY
    - DOMAIN,steamuserimages-a.akamaihd.net,PROXY
    - DOMAIN,steamvideo-a.akamaihd.net,PROXY

    # 3. 通用代理兜底：国内直连，其他流量走代理
    - GEOIP,CN,DIRECT
    - MATCH,PROXY

rules:
  # GEOIP DOWNLOAD PATH https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.metadb
  - GEOIP,CN,DIRECT
  - MATCH,PROXY
